### PR TITLE
Fixed localization and added zh_cn locale

### PR DESCRIPTION
**Pull request by TCreopargh**

### CODE REVIEW

**Comment by TCreopargh** [comment]
I forgot to change the version name in the main class and mcmod.info, make sure to change these.

**Comment by Cornit** [comment]
Is it working? I've done the exact same thing. xD

**Comment by TCreopargh** [comment]
It works like a charm, I don't know why it doesn't work for you

**Comment by Cornit** [comment]
Well, thank you!!! I'll merge it.

**Pull request merged**
